FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

COPY ["Shared/Shared.csproj", "Shared/"]
COPY ["ReportingService/Reporting.Api/Reporting.Api.csproj", "ReportingService/Reporting.Api/"]
COPY ["ReportingService/Reporting.Application/Reporting.Application.csproj", "ReportingService/Reporting.Application/"]
COPY ["ReportingService/Reporting.Domain/Reporting.Domain.csproj", "ReportingService/Reporting.Domain/"]
COPY ["ReportingService/Reporting.Infrastructure/Reporting.Infrastructure.csproj", "ReportingService/Reporting.Infrastructure/"]

RUN dotnet restore "ReportingService/Reporting.Api/Reporting.Api.csproj"

COPY . .

WORKDIR "/src/ReportingService/Reporting.Api"
RUN dotnet publish "Reporting.Api.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "Reporting.Api.dll"]