FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

COPY ["Shared/Shared.csproj", "Shared/"]
COPY ["PolicyService/Policy.Worker/Policy.Worker.csproj", "PolicyService/Policy.Worker/"]
COPY ["PolicyService/Policy.Application/Policy.Application.csproj", "PolicyService/Policy.Application/"]
COPY ["PolicyService/Policy.Domain/Policy.Domain.csproj", "PolicyService/Policy.Domain/"]
COPY ["PolicyService/Policy.Infrastructure/Policy.Infrastructure.csproj", "PolicyService/Policy.Infrastructure/"]

RUN dotnet restore "PolicyService/Policy.Worker/Policy.Worker.csproj"

COPY . .

WORKDIR "/src/PolicyService/Policy.Worker"
RUN dotnet publish "Policy.Worker.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "Policy.Worker.dll"]