FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

COPY ["Gateway.Api/Gateway.Api.csproj", "Gateway.Api/"]

RUN dotnet restore "Gateway.Api/Gateway.Api.csproj"

COPY . .

WORKDIR "/src/Gateway.Api"
RUN dotnet publish "Gateway.Api.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .

ENV ASPNETCORE_ENVIRONMENT=Docker

ENTRYPOINT ["dotnet", "Gateway.Api.dll"]
