FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

COPY ["Shared/Shared.csproj", "Shared/"]
COPY ["NotificationService/Notification.Worker/Notification.Worker.csproj", "NotificationService/Notification.Worker/"]
COPY ["NotificationService/Notification.Application/Notification.Application.csproj", "NotificationService/Notification.Application/"]
COPY ["NotificationService/Notification.Domain/Notification.Domain.csproj", "NotificationService/Notification.Domain/"]
COPY ["NotificationService/Notification.Infrastructure/Notification.Infrastructure.csproj", "NotificationService/Notification.Infrastructure/"]

RUN dotnet restore "NotificationService/Notification.Worker/Notification.Worker.csproj"

COPY . .

WORKDIR "/src/NotificationService/Notification.Worker"
RUN dotnet publish "Notification.Worker.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "Notification.Worker.dll"]