FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

COPY ["Shared/Shared.csproj", "Shared/"]
COPY ["PaymentService/Payment.Api/Payment.Api.csproj", "PaymentService/Payment.Api/"]
COPY ["PaymentService/Payment.Application/Payment.Application.csproj", "PaymentService/Payment.Application/"]
COPY ["PaymentService/Payment.Domain/Payment.Domain.csproj", "PaymentService/Payment.Domain/"]
COPY ["PaymentService/Payment.Infrastructure/Payment.Infrastructure.csproj", "PaymentService/Payment.Infrastructure/"]

RUN dotnet restore "PaymentService/Payment.Api/Payment.Api.csproj"

COPY . .

WORKDIR "/src/PaymentService/Payment.Api"
RUN dotnet publish "Payment.Api.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "Payment.Api.dll"]